Repository sonatype-nexus-community/the-cla, pull requests merged in 2024-08, with the labels that each got.

#94 doc: document how to release
  README.md
Labels: documentation

#96 chore(ci): use Sonatype Platform URL from variable not secret
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: enhancement

#95 feat: add additional data capture - CLA Text URL and CLA Text
  .example.env
  .gitignore
  Makefile
  db/db.go
  db/db_test.go
  db/migrations/002_cla_url_text.down.sql
  db/migrations/002_cla_url_text.up.sql
  package.json
  server.go
  server_test.go
  src/Body/Body.tsx
  types/types.go
  yarn.lock
Labels: enhancement

#97 feat: email notifications on signature
  .example.env
  README.md
  main.tf
  server.go
  server_test.go
  variables.tf
  yarn.lock
Labels: enhancement

#98 fix: hide test email endpoint on the authenticated `/info` subpath
  server.go
Labels: enhancement

#99 fix: handle CLA URL correctly from UI
  server.go
Labels: bug

#100 fix: CLS Typo
  server.go
  server_test.go
Labels: bug
